### ISSUE TITLE
Acknowledgment  location

### ISSUE THREAD

**Issue by JavierRefuerzo** [jimboca/udi-poly-notification#13]
Hi Jimbo,

Just want to make a suggestion on moving/duplicating/linking the Acknowledgment to the top of the POLYGLOT_CONFIG.md. Just to help new users set the param.

**Comment by jimboca** [comment]
Yes, that's fine with me, whatever can help new users. Go ahead and include that in your PR.

**Comment by JavierRefuerzo** [comment]
Closing this as I overlooked that the Notification Notice is present in the UI below the Notification Tab.
