### ISSUE TITLE
Command Name discrepancy Query/Refresh

### ISSUE THREAD

**Issue by JavierRefuerzo** [jimboca/udi-poly-notification#16]
Hi Jimbo,

I have found a CMD NAME discrepancy for the Query button.   Would you like this button to be named "Refresh" or "Query"? 

 In Node Def the `<cmd id="QUERY"/>` has no mapping in the NLS. In the NLS `CMD-ctl-REFRESH-NAME = Refresh` has no refrence in the Node Def.

From Node Def
`<cmd id="QUERY"/>`

From NLS
`# controller
ND-controller-NAME = Notification Controller

CMD-ctl-REFRESH-NAME = Refresh
CMD-ctl-PROCESS_CONFIG-NAME = Process Config
CMD-ctl-BUILD_PROFILE-NAME = Build Profile
CMD-ctl-INSTALL_PROFILE-NAME = Install Profile`

**Comment by jimboca** [comment]
Hey Javi, In think QUERY is a default that you don't have to define in the nls, when it's not defined that means it doesn't show up at the bottom of the AC page, but you can still right click on a node and select query.
I think refresh was meant to re-load everything from pushover, but I can't remember for sure.

**Comment by JavierRefuerzo** [comment]
Thanks Jimbo, 

"Query" (mixed case) is showing at the bottom of the Admin Console,  your assumption makes sense as it does not show "QUERY" (cap).  I'll look into the "QUERY" Def  a little more when I have some free time as this may through errors for U.I developers without a mapping.
