### ISSUE TITLE
api_key location

### ISSUE THREAD

**Issue by BoomerangThree** [jimboca/udi-poly-notification#17]
I've looked, and apologize if I missed it right in front of me, but I cannot locate the api_key for pushover.  I have an working account and apps, now trying to setup the node server.  I have my user_key, but cannot locate the api_key either here or on pushover.

Regards, Jeff.

**Comment by BoomerangThree** [comment]
Sorry for the wasted time, but after my message I did another search and found the page to create it.

**Comment by JavierRefuerzo** [comment]
If you look in the Node server under configuration press the configuration_help button, this will automatically create an API key with the UD Logo

**Comment by BoomerangThree** [comment]
Hi Jim,

Thanks for the reply.  So, when I ress the configuration_help button the following is displayed.  So the api_key below is what I should be using?

**Comment by JavierRefuerzo** [comment]
Sorry, forgot to say there is a link in text the configuration_help about half way down.  This just makes it easier, but you can create your own

**Comment by BoomerangThree** [comment]
Hi Jim,

I have it working with the api_key I created with Pushover, so all good.

However, I still cannot find the link in text in the configuration_help you referred to.  I know I’m getting old and it’s probably right in front of my eyes, but just in case, you might highlight it to be easier to find, that is unless it already is and I’m losing it.  :)

Regards, 

P.S.  Nice work.  With your node server and Pushover my notifications went from 12-15 secs to almost instant.

**Comment by JavierRefuerzo** [comment]
I'm not Jimbo, but he did do great work on this..... The link has the text "clone the Universal Devices application"

**Comment by jimboca** [comment]
Thanks Javi, and Thanks Jeff!  It's here:

![image](https://user-images.githubusercontent.com/1578044/92842863-ecb3b400-f398-11ea-931d-9ba0fbbd913c.png)

**Comment by BoomerangThree** [comment]
Hi Javi,

Ok., found it.  It’s in https://github.com/jimboca/udi-poly-notification/blob/master/POLYGLOT_CONFIG.md <https://github.com/jimboca/udi-poly-notification/blob/master/POLYGLOT_CONFIG.md> and I was looking in the Configuration Help page on Polisy and the Pushover node server.

All good.

**Comment by BoomerangThree** [comment]
I’m not trying to be a pain, and hopefully this helps both of us, but my page looks like this, no link.   Is there another Configuration Help page that I’m missing.

Again, it’s working great, just trying to help you guys out, that is unless I’m completely lost.  ;)

**Comment by jimboca** [comment]
That's strange, can you screenshot it? So I can see what you have?

**Comment by BoomerangThree** [comment]
Jeff Mason
…………………………………………………
eMail         - Jeffrey.Mason@gmail.com
(aka BoomerangThree, because life is a Boomerang, pay it forward)
FlipBoard  - @BoomerangThree
Twitter       - BoomerangThree
