### ISSUE TITLE
Add more retry and timeouts to message posting

### ISSUE THREAD

**Issue by jimboca** [jimboca/udi-poly-notification#19]
Also, may want to push sending the message into a thread so it doesn't block?

**Comment by MrBill12** [comment]
From my point of view the greatest issue seems to be http timeout, or lack of http return code.

**Comment by jimboca** [comment]
Return codes:
- 200: all good
- 4xx: Error that can't be fixed, no retry
- 500 or anything else, can retry after 5 seconds

**Comment by jimboca** [comment]
When the nodeserver sends a message and there is an error it will set the Service Node's Last Status and Error, then will continue to retry sending the message every 5 seconds, up to 10 times.

Should it continually retry or increase to 720 retries which is an hour or more?

**Comment by jimboca** [comment]
I've changed the retry to forever instead of 10.  I have concerns about this, but that is the best option for now.
